- name: Set up Gradle
  uses: actions/setup-java@v4
  with:
    java-version: '21'
    distribution: 'temurin'
    cache: gradle

- name: Build with Gradle
  run: ./gradlew clean build

- name: Upload built JAR
  uses: actions/upload-artifact@v4
  with:
    name: payment-service-jar
    path: build/libs/*.jar